### ISSUE TITLE
Slight Gui Modifications conflict with Konkrete on 1.18 

### ISSUE THREAD

**Issue by Disguys** [shedaniel/slight-gui-modifications#48]
Hello, I decided to update my modpack to version 1.18, left those mods that have been updated to 1.18, saw that your mod also works on 1.18, installed all the necessary libraries, but for some reason it conflicts with Konkrete libary. Without other mods, it runs smoothly.
[crash-2021-12-06_14.04.41-client.txt](https://github.com/shedaniel/slight-gui-modifications/files/7659457/crash-2021-12-06_14.04.41-client.txt)

**Comment by Disguys** [comment]
Please author mod SGM, answer
https://github.com/Keksuccino/Konkrete/issues/8

**Comment by shedaniel** [comment]
I believe that the two mods have similar functionalities and therefore is fundamentally incompatible.

**Comment by EGOIST1372** [comment]
I'm happy to say that with latest [Konkrete](https://www.curseforge.com/minecraft/mc-mods/konkrete-fabric) and latest [Slight GUI modifications](https://www.curseforge.com/minecraft/mc-mods/slight-gui-modifications) and latest [ARRP](https://www.curseforge.com/minecraft/mc-mods/arrp) and latest [architectury api](https://www.curseforge.com/minecraft/mc-mods/architectury-fabric) updates there is no crash at startup of the game and game starts and for me that really loved Satisfying Screenshots feature of SGM it works great without problem. 
But I don't know what happens if you change elements in SGM setting that interfere with konkrete/fancy menu mod and I have no reason to find out. just here to say it's not crashing anymore and Satisfying Screenshots works for me :D

fabric loader v0.13.3 1.18.2
fabric api v0.48.0 1.18.2
slight GUI modification v2.1.0 1.18.2
Konkrete [Fabric] v1.3.3-1 1.18.2
arrp v0.5.7
Architectury v4.1.39 1.18.2
